id = "tron-legacy"
name = "Tron Legacy"
version = "1.1.7"
schema_version = 1
authors = ["Bret Comnes <bcomnes@gmail.com>"]
description = "A port of the Tron Legacy theme for Zed"
repository = "https://github.com/bcomnes/zed-theme-tron-legacy"
